services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: its-mytabs:local
        ports:
            # Host Port:Container Port
            - "47777:47777"
        # Fedora&Podman specific
        security_opt:
            - label=disable
        userns_mode: "keep-id:uid=1993,gid=1993"
        environment:
            MYTABS_DISABLE_AUTH: "true"
            MYTABS_IMPORT_ROOTS: ${MYTABS_IMPORT_ROOTS:-/srv/tabs/import}
        volumes:
            # Host Path:Container Path
            - ./data:/app/data
            - ./import:${MYTABS_IMPORT_ROOTS:-/srv/tabs/import}:ro
        restart: unless-stopped
